[package]
name = "cli"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[[bin]]
name = "ai"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
homedir = "0.2.1"
serde = "1.0.202"
toml = "0.8.13"
