[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.117"
ureq = { "version"="2.9.7", features=["json"] }

[dev-dependencies]
httpmock = "0.7.0"
pretty_assertions = "1.4.0"
